### ISSUE TITLE
As a user I want to be able to signup for market intel on www.dev1.inman.com

### ISSUE THREAD

**Issue by marcelaph** [partnerhero/Hub-Optimization#2]

**Comment by corellanaph** [comment]
1. Signup took a lot of time and at the end the charge was paid twice.
2. Login failed.

![market intel signup](https://cloud.githubusercontent.com/assets/24833309/21614421/03777610-d19f-11e6-9e5c-f32ac462e62c.png)

![market intel login](https://cloud.githubusercontent.com/assets/24833309/21614840/c80b77aa-d1a0-11e6-9933-a9e19635577b.png)

**Comment by corellanaph** [comment]
1. Task closed. https://app.asana.com/0/237284520792731/237749577931477
2. Task closed. https://app.asana.com/0/237284520792731/237749577931478
