### ISSUE TITLE
As a user I want to be able to signup on select+ on www.dev1.inman.com

### ISSUE THREAD

**Issue by marcelaph** [partnerhero/Hub-Optimization#3]

**Comment by corellanaph** [comment]
1. When clicking on "Sign up now" button, it opens production site: https://www.inman.com/select/
2. Select+ login fails, the user has Select+ extension.
![login select](https://cloud.githubusercontent.com/assets/24833309/21613274/2e984e5a-d19a-11e6-98e2-aa8104c997c1.png)

**Comment by corellanaph** [comment]
1. Task closed. https://app.asana.com/0/237284520792731/237749577931475
